# Generated by Django 4.2.9 on 2026-08-14 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_room_cleaning_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Split AC Unit', 'Wall Socket (near bed)', 'Bathroom Tap'", max_length=150)),
                ('category', models.CharField(choices=[('appliance', 'Appliance (AC, TV, Fridge...)'), ('electrical', 'Electrical (Socket, Switch, Wiring...)'), ('plumbing', 'Plumbing (Tap, Shower, Toilet...)'), ('furniture', 'Furniture'), ('fixture', 'Fixture (Light, Fan, Door, Window...)'), ('other', 'Other')], default='other', max_length=20)),
                ('location_note', models.CharField(blank=True, help_text="For common-area assets only, e.g. 'Main Lobby', '2nd Floor Corridor'.", max_length=150)),
                ('status', models.CharField(choices=[('working', 'Working'), ('broken', 'Broken'), ('under_repair', 'Under Repair'), ('decommissioned', 'Decommissioned')], db_index=True, default='working', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, help_text='Leave blank for a common-area asset (lobby, corridor, restaurant, etc.) and use Location note instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='rooms.room')),
            ],
            options={
                'db_table': 'property_assets',
                'ordering': ['room__room_number', 'location_note', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('fixed', 'Fixed')], default='reported', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('fix_notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='assets.propertyasset')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_issues_fixed', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_issues_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_issue_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
