# Generated by Django 4.2.9 on 2026-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_propertyasset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyasset',
            name='department',
            field=models.CharField(choices=[('frontdesk', 'Front Desk'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping (incl. all guest rooms)'), ('laundry', 'Laundry'), ('shared', 'Shared / Common Area — visible centrally only')], default='shared', help_text="Whose day-to-day view this shows up in. Room-tied assets are almost always 'housekeeping' — she's the one who notices/reports damage during cleaning. Front Desk/Manager/Owner always see everything regardless of this tag (the central, unrestricted view).", max_length=15),
        ),
    ]
