# Generated by Django 4.2.9 on 2026-08-14 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, help_text='Optional internal code. Auto-generated if left blank.', max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('bottle', 'Bottle'), ('can', 'Can'), ('crate', 'Crate'), ('carton', 'Carton'), ('bag', 'Bag'), ('kg', 'Kilogram'), ('litre', 'Litre'), ('piece', 'Piece'), ('pack', 'Pack'), ('roll', 'Roll'), ('bunch', 'Bunch'), ('box', 'Box')], default='piece', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='What the hotel pays to acquire one unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='What a guest is charged for one unit — set for drinks sold at the Bar; leave blank for items that are only consumed, like kitchen ingredients.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_threshold', models.PositiveIntegerField(default=5, help_text='Flag this item as low-stock at this location when its quantity falls to or below this number.')),
                ('expiry_tracked', models.BooleanField(default=False, help_text='Whether individual batches of this item should track an expiry date.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('store', 'Store'), ('bar', 'Bar'), ('kitchen', 'Kitchen')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_stock_balances',
                'ordering': ['item__name', 'location'],
                'unique_together': {('item', 'location')},
            },
        ),
    ]
