# Generated by Django 4.2.9 on 2026-08-14 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_stockrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('store', 'Store'), ('bar', 'Bar'), ('kitchen', 'Kitchen')], max_length=20)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resulting_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_logs', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
