# Generated by Django 4.2.9 on 2026-08-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_branch'),
        ('inventory', '0004_reset_stock_for_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'ordering': ['item__name', 'hotel__branch', 'location']},
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockadjustmentlog',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_logs', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='hotel',
            field=models.ForeignKey(help_text="Which branch this stock count belongs to. The same item has an independent quantity at each branch — Coca-Cola at Fwavwei's Bar is a completely different number from Coca-Cola at Zarmaganda's Bar.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='stockrequisition',
            name='hotel',
            field=models.ForeignKey(help_text="Which branch this request and fulfillment moves stock within — a Bar Staff at Fwavwei can only request from, and be fulfilled by, Fwavwei's own Store.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requisitions', to='hotels.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('item', 'hotel', 'location')},
        ),
    ]
