# Generated by Django 4.2.9 on 2026-08-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_branch_specific_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('can', 'Can'), ('plastic', 'Plastic'), ('crate', 'Crate'), ('carton', 'Carton'), ('bag', 'Bag'), ('kg', 'Kilogram'), ('litre', 'Litre'), ('piece', 'Piece'), ('pack', 'Pack'), ('roll', 'Roll'), ('bunch', 'Bunch'), ('box', 'Box')], default='piece', max_length=20),
        ),
    ]
