# Generated by Django 4.2.9 on 2026-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_housekeeping_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar only'), ('kitchen', 'Kitchen only'), ('housekeeping', 'Housekeeping only'), ('laundry', 'Laundry only'), ('shared', 'Shared / Store only')], default='shared', help_text="Who requests items in this category from the Store. 'Bar only' / 'Kitchen only' / 'Housekeeping only' hides it from every OTHER department's Inventory screen — a Kitchen Staff account never sees a Bar-only or Housekeeping-only category and vice versa. 'Shared / Store only' is visible to all of them (or none, if it's something only the Store Keeper handles directly, like cleaning supplies).", max_length=15),
        ),
        migrations.AlterField(
            model_name='stockadjustmentlog',
            name='location',
            field=models.CharField(choices=[('store', 'Store'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='location',
            field=models.CharField(choices=[('store', 'Store'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='destination',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry')], max_length=20),
        ),
    ]
