# Generated by Django 4.2.9 on 2026-05-20 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='check', max_length=100)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('tech', 'Technology'), ('comfort', 'Comfort'), ('bathroom', 'Bathroom'), ('entertainment', 'Entertainment'), ('dining', 'Dining'), ('security', 'Security')], default='basic', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekend_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holiday_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin'), ('suite', 'Suite')], default='king', max_length=20)),
                ('num_beds', models.PositiveIntegerField(default=1)),
                ('room_size_sqm', models.DecimalField(decimal_places=1, default=30, max_digits=6)),
                ('num_bathrooms', models.PositiveIntegerField(default=1)),
                ('has_living_room', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='rooms/thumbnails/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_categories', to='rooms.amenity')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'db_table': 'room_categories',
                'ordering': ['sort_order', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comfort', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.roomcategory')),
            ],
            options={
                'db_table': 'room_reviews',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rooms/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory')),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('out_of_order', 'Out of Order')], db_index=True, default='available', max_length=20)),
                ('is_smoking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('view_type', models.CharField(choices=[('garden', 'Garden'), ('city', 'City'), ('pool', 'Pool'), ('courtyard', 'Courtyard')], default='city', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomcategory')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
    ]
