# Generated by Django 4.2.9 on 2026-08-12 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_merge_duplicate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rooms/room_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room')),
            ],
            options={
                'db_table': 'room_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
