# Generated by Django 4.2.9 on 2026-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_started_at',
            field=models.DateTimeField(blank=True, help_text="When this room entered 'cleaning' status at checkout — used to auto-release it back to 'available' after CLEANING_BUFFER_MINUTES.", null=True),
        ),
    ]
