# Generated by Django 4.2.9 on 2026-08-11 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_booking_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_due_at_request', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, help_text='Staff note on why checkout is needed despite balance owed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_approvals', to='bookings.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkout_approval_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
