# Generated by Django 4.2.9 on 2026-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_checkoutapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_verified_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
