# Generated by Django 4.2.9 on 2026-08-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_booking_checkin_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinIdentityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('likely_match', 'Likely match'), ('uncertain', 'Uncertain'), ('likely_mismatch', 'Likely mismatch'), ('error', 'Could not complete check')], max_length=20)),
                ('confidence_note', models.TextField(blank=True)),
                ('reference_source', models.CharField(choices=[('avatar', "Guest's saved profile photo"), ('uploaded_id', 'ID document photographed at check-in')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_checks', to='bookings.booking')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_checks_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkin_identity_checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
