# Generated by Django 4.2.9 on 2026-08-11 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('raw_signals', models.JSONField(default=dict)),
                ('summary_text', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_audit_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
