# Generated by Django 4.2.9 on 2026-05-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('capacity_seated', models.PositiveIntegerField()),
                ('capacity_cocktail', models.PositiveIntegerField()),
                ('capacity_banquet', models.PositiveIntegerField()),
                ('size_sqm', models.DecimalField(decimal_places=1, max_digits=8)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_half_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_full_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_weekend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('has_projector', models.BooleanField(default=True)),
                ('has_sound_system', models.BooleanField(default=True)),
                ('has_microphone', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_stage', models.BooleanField(default=False)),
                ('has_dance_floor', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/halls/thumbnails/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_halls',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventHallImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/halls/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventhall')),
            ],
            options={
                'db_table': 'event_hall_images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate/Conference'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('naming', 'Naming Ceremony'), ('burial', 'Burial/Memorial'), ('product_launch', 'Product Launch'), ('concert', 'Concert'), ('custom', 'Custom Event')], default='corporate', max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('setup_time', models.TimeField()),
                ('expected_guests', models.PositiveIntegerField()),
                ('setup_style', models.CharField(choices=[('theatre', 'Theatre'), ('classroom', 'Classroom'), ('banquet', 'Banquet/Round Tables'), ('boardroom', 'Boardroom'), ('cocktail', 'Cocktail/Standing'), ('u_shape', 'U-Shape')], default='theatre', max_length=20)),
                ('catering_required', models.BooleanField(default=False)),
                ('catering_notes', models.TextField(blank=True)),
                ('decoration_required', models.BooleanField(default=False)),
                ('photography_required', models.BooleanField(default=False)),
                ('mc_required', models.BooleanField(default=False)),
                ('live_band_required', models.BooleanField(default=False)),
                ('dj_required', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('hall_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extras_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('catering_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.eventhall')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
