# Generated by Django 4.2.9 on 2026-08-26 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_room_cleaning_started_at'),
        ('hotels', '0005_rename_fwavwei_to_rayfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryPriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Shirt', 'Trouser', 'Bedsheet', 'Suit (2pc)'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items stay on old tickets but drop off the guest price list and the staff picker.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_price_items', to='hotels.hotel')),
            ],
            options={
                'db_table': 'laundry_price_items',
                'ordering': ['name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LaundryTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(help_text='Who to address in the ready notification.', max_length=150)),
                ('guest_email', models.EmailField(blank=True, help_text='If left blank, no notification email can be sent — staff must tell the guest directly.', max_length=254)),
                ('guest_phone', models.CharField(blank=True, help_text='Informational only — no SMS is sent from this field.', max_length=30)),
                ('notes', models.TextField(blank=True, help_text="Anything not covered by the line items below, e.g. 'extra starch requested'.")),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items — computed when the ticket is created.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'In Progress'), ('ready', 'Ready for Pickup')], db_index=True, default='pending', max_length=10)),
                ('notified', models.BooleanField(default=False, help_text='True once a ready-notification email actually sent successfully.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_tickets', to='hotels.hotel')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_tickets_logged', to=settings.AUTH_USER_MODEL)),
                ('ready_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_tickets_marked_ready', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Which room the guest is staying in, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_tickets', to='rooms.room')),
            ],
            options={
                'db_table': 'laundry_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundryTicketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text="Snapshot of the price item's name at the time of this ticket.", max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot of the price at the time of this ticket.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_lines', to='laundry.laundrypriceitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='laundry.laundryticket')),
            ],
            options={
                'db_table': 'laundry_ticket_items',
            },
        ),
    ]
