# Generated by Django 4.2.9 on 2026-08-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryticket',
            name='guest_account',
            field=models.ForeignKey(blank=True, help_text="The guest's real account, if Laundry Staff found one — required for the guest to see and pay for this ticket in-app. name/email/phone below are a snapshot taken from this account at creation time (or typed manually if no account was matched).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundryticket',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Set True by the payments app once an in-app payment for this ticket succeeds.'),
        ),
        migrations.AddField(
            model_name='laundryticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
