# Generated by Django 4.2.9 on 2026-08-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockrequisition'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text="Optional — link this menu item to a tracked stock item (e.g. a specific bottled drink). When an order for it is marked Delivered, that item's stock is automatically decremented at Bar or Kitchen (inferred from this menu item's category type). Leave blank for dishes that don't map to a single stock-keeping unit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Whether linked inventory items have already been decremented for this order — prevents double-deducting if status is changed more than once.'),
        ),
    ]
