# Generated by Django 4.2.9 on 2026-08-15 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_branch'),
        ('orders', '0002_menuitem_inventory_item_order_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text="Which branch this order belongs to — inferred automatically from the guest's room/booking at creation time (see CreateOrderView), so guests never have to pick a branch themselves. Determines which branch's Kitchen/Bar staff see this order, and which branch's stock gets decremented on delivery.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hotels.hotel'),
        ),
    ]
