# Generated by Django 4.2.9 on 2026-08-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_branch'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text="Which branch this account belongs to. Required for Manager, Front Desk Staff, Store Keeper, Bar Staff, and Kitchen Staff — they only see and manage that branch's rooms, inventory, and orders. Left blank for Owner/Admin (who sees every branch) and Guest (who isn't tied to one). An account with a role that needs a branch but has none set sees nothing at all, on purpose — never silently 'all branches'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hotels.hotel'),
        ),
    ]
