# Generated by Django 4.2.9 on 2026-08-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Front Desk Staff'), ('store_keeper', 'Store Keeper'), ('bar_staff', 'Bar Staff'), ('kitchen_staff', 'Kitchen Staff'), ('housekeeper', 'Housekeeper'), ('manager', 'Manager'), ('admin', 'Admin')], db_index=True, default='guest', max_length=20),
        ),
    ]
