# Generated by Django 4.2.9 on 2026-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_fix_branch_spelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='branch',
            field=models.CharField(choices=[('zaramaganda', 'Zarmaganda'), ('fwawei', 'Fwavwei')], max_length=20, unique=True),
        ),
    ]
