# Generated by Django 4.2.9 on 2026-05-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('booking', 'Room Booking'), ('order', 'Food/Drink Order'), ('event', 'Event Hall'), ('gym', 'Gym Session')], max_length=20)),
                ('method', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('ussd', 'USSD'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pos', 'POS')], max_length=30)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=20)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('gateway_reference', models.CharField(blank=True, max_length=300)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('flw_ref', models.CharField(blank=True, max_length=300)),
                ('paystack_ref', models.CharField(blank=True, max_length=300)),
                ('access_code', models.CharField(blank=True, max_length=300)),
                ('stripe_session_id', models.CharField(blank=True, max_length=300)),
                ('paypal_order_id', models.CharField(blank=True, max_length=300)),
                ('ussd_code', models.CharField(blank=True, max_length=50)),
                ('ussd_bank', models.CharField(blank=True, max_length=100)),
                ('virtual_acct_num', models.CharField(blank=True, max_length=20)),
                ('virtual_acct_bk', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('ussd_code', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_session', to='payments.payment')),
            ],
            options={
                'db_table': 'ussd_sessions',
            },
        ),
        migrations.CreateModel(
            name='BankTransferSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=300)),
                ('sort_code', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_session', to='payments.payment')),
            ],
            options={
                'db_table': 'bank_transfer_sessions',
            },
        ),
    ]
