# Generated by Django 4.2.9 on 2026-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_monnify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('booking', 'Room Booking'), ('order', 'Food/Drink Order'), ('event', 'Event Hall'), ('gym', 'Gym Session'), ('laundry', 'Laundry Service')], max_length=20),
        ),
    ]
